Models/Administradores.cs
namespace Projeto_final.Models
{
    public class Administradores
    {
        public string Nome {get;set;}
        public string Email {get;set;}
        public string Senha {get;set;}

    }
}

Models/Cadastro.cs
using System;

namespace Projeto_final.Models
{
    public class Cadastro
    {
        public int Id {get;set;}
        public string Nome {get;set;}
        public string Email {get;set;}
        public string Senha {get;set;}
        public string Administrador {get;set;}
        public DateTime DataNascimento {get;set;}
    }
}

Models/Comentario.cs
using System;

namespace Projeto_final.Models
{
    public class Comentario
    {
        public int Id {get;set;}
        public Cadastro Cadastro {get;set;}
        public string Texto {get;set;}
        public DateTime DataCricacao {get;set;}
        public bool Status {get;set;}

    }
}

Models/ErrorView.cs
using System;

namespace Projeto_final.Models
{
    public class ErrorViewModel
    {
         public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CadastroController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projeto_final.Models;
using Projeto_final.Repositorios;

namespace Projeto_final.Controllers
{
    public class CadastroController : Controller
    {
        CadastroRepositorio cadastroRepositorio = new CadastroRepositorio();

        [HttpGet]
        public IActionResult Index()
        {
            ViewData["NomeView"] = "Cadastro";
            return View();
        }

        
        [HttpPost]
        public IActionResult RegistrarUsuario(IFormCollection form)
        {   
            Cadastro cadastro = new Cadastro();
            cadastro.Nome = form["nome"];
            cadastro.Email = form["email"];
            cadastro.Senha = form["senha"];
            cadastro.DataNascimento = DateTime.Parse(form["dataNascimento"]);

            cadastroRepositorio.RegistrarUsuario(cadastro);

            ViewData["NomeView"] = "Home";
            return RedirectToAction("Index", "Login");
       }








    }
}

Controllers/ComentarioController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projeto_final.Models;
using Projeto_final.Repositorios;

namespace Projeto_final.Controllers
{
    public class ComentarioController : Controller
    {
        private const string SESSION_EMAIL = "_EMAIL";
        private const string SESSION_CLIENTE = "_CLIENTE";

        public IActionResult Index() 
        {
            ViewData["User"] = HttpContext.Session.GetString(SESSION_EMAIL);
            return View();
        }

        [HttpPost]
        public IActionResult Depoimento (IFormCollection form)
        {
            Comentario comentario = new Comentario();
            CadastroRepositorio cadastroRepositorio = new CadastroRepositorio();

            var email = HttpContext.Session.GetString(SESSION_EMAIL);
            var cadastroRetornado = cadastroRepositorio.ObterPor(email);

            comentario.Cadastro = cadastroRetornado;
            comentario.Texto = form["comentario"];
            

            ComentarioRepositorio cr = new ComentarioRepositorio();
            cr.InserirComentario(comentario);

            return RedirectToAction("Index", "Home");

        }

    }
}

Controllers/HomeController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projeto_final.Models;

namespace Projeto_final.Controllers
{
    public class HomeController : Controller
    {
        private const string SESSION_EMAIL = "_EMAIL";
        private const string SESSION_CLIENTE = "_CLIENTE";

        [HttpGet]
        public IActionResult Index()
        {
            ViewData["User"] = HttpContext.Session.GetString(SESSION_EMAIL);
            ViewData["NomeView"] = "Home";
            return View();
        }

       [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
       
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projeto_final.Models;
using Projeto_final.Repositorios;

namespace Projeto_final.Controllers
{
    public class LoginController : Controller
    {
        CadastroRepositorio cadastroRepositorio = new CadastroRepositorio();

        private const string SESSION_EMAIL = "_EMAIL";
        private const string SESSION_CLIENTE = "_CLIENTE";
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Logar(IFormCollection form)
        {
            var cadastre = form["email"];
            var senha = form["senha"];

            var lista = cadastroRepositorio.Listar();

            foreach (var item in lista)
            {
                if (lista != null && item.Senha.Equals(senha) && item.Email.Equals(cadastre))
                {
                    HttpContext.Session.SetString(SESSION_EMAIL, cadastre);
                    HttpContext.Session.SetString(SESSION_CLIENTE, item.Nome);
                }
            }
            return RedirectToAction("Index", "Comentario");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove(SESSION_EMAIL);
            HttpContext.Session.Remove(SESSION_CLIENTE);
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/QuemSomosController.cs
using Microsoft.AspNetCore.Mvc;

namespace Projeto_final.Controllers
{
    public class QuemSomosController : Controller
    {

        [HttpGet]
        public IActionResult Index(){

            ViewData["NomeView"] = "QuemSomos";
            return View();
        
        }
    }
}

Controllers/SacController.cs
using Microsoft.AspNetCore.Mvc;

namespace Projeto_final.Controllers
{
    public class SacController : Controller
    {
         [HttpGet]
          public IActionResult Index()
        {
            ViewData["NomeView"] = "Cadastro";
            return View();
        }
    }
}

Views/Administrador/Cadastros.cshtml
@{
    Layout = "_Layout";
    
}

Views/Administrador/Index.cshtml
@{
Layout = "_Layout";
}

Views/Cadastro/Index.cshtml
@{
    Layout = "_Layout";
}
    <link rel="stylesheet" href="css/cadastro.css">


    <section id="cadastro">
       
            <div id="area">
                    <form action="Cadastro/RegistrarUsuario" method="POST" id="formulario" autocomplete="off">
                      <fieldset>
                        <legend>Cadastre-se</legend>
                        <div><label class="nome">Nome:</label><input class="campo_nome" type="text" name="nome"><br></div>
                        <div><label class="email">Email:</label><input class="campo_email" type="text" name="email"><br></div>
                         <div><label class="senha">Senha:</label><input class="campo_senha" type="text" name="senha"><br></div>
                        <div><label class="data">Data de nascimento:</label><input class="campo_data" type="date" name="dataNascimento"><br></div>
                        <input type="submit" value="Enviar" class="enviar">
                      </fieldset>
                    </form>
                </div>
            </section>
            <section>

                <p>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </p>.
                
            </section>


</html>

Views/Comentario/Index.cshtml
@{
    Layout = "_Layout"; 
    ViewData["TituloPag"] = "Comentarios";
}   
<head>

<!-- <link rel="stylesheet" href="css/style.css"> -->
<link rel="stylesheet" href="css/comentario.css">

</head>


<div id="area">
     <form method="POST" action='@Url.Action("Depoimento", "Comentario")' id="formulario">
    <fieldset>
        <legend>comentario</legend>
        <div class="pridiv"><input class="comentario" type="text" name="comentario" required><br></div>
        <input type="submit" value="Enviar" class="enviar">
    </fieldset>
    </form>

Views/Home/Index.cshtml
@{
    Layout = "_Layout";
   
}
 <link rel="stylesheet" href="/css/style.css" type="text/css">
        <!-- fim da nav -->
        <!-- inicio do banner -->
        <section class="banner">
            <div class="paragrafo">
                    <h2 class="h23">Plano Grátis</h2>
            <p>Possibilidade de gerenciar um fúncionario.
                    <br>
                    <br>
                    Retorno de pacote de 48 horas para
                    problemas técnicos <br> ou dúvidas.
                </p>
            </div>
            <a href='@Url.Action("Index", "Cadastro")#'><img class="pc_uma" src="img/computadores-1.jpg" alt="pc"></a>
        </section>
    </header>
    <!-- planos -->
    <section class="planos">
        <h2>Planos e Pacotes</h2>
        <h3 class="h3">1º Plano</h3>
        <div class="textos">
            <p>29,99 por mês
                <br>Possibilidade de gerenciar cinco fúncionarios
                <br>Retorno de pacote de 24 horas.</p>
        </div>
        <div class="pcs"><a href='@Url.Action("Index", "Cadastro")#'><img src="img/computadores-1.jpg" alt=""></a></div>
        <h3 class="h3">2° Plano </h3>
        <div class="textos">
            <p>149,99 por mês
                <br>Possibilidade de gerenciar 50 fúncionarios
                <br>Retorno de pacote de 12 horas.</p>
        </div>
        <div class="pcs"><a href='@Url.Action("Index", "Cadastro")#'><img src="img/computadores-2.jpg" alt=""></a></div>
        <h3 class="h3">3° Plano</h3>
        <div class="textos">
            <p>299,99 por mês
                <br>Possibilidade de gerenciar 500 fúncionarios
                <br>Retorno de pacote de 2 horas.</p>
        </div>
        <div class="pcs"><a href='@Url.Action("Index", "Cadastro")#'><img src="img/computadores-3.jpg" alt=""></a></div>
        <h3 class="h3">4° Plano</h3>
        <div class="textos">
            <p>A definir por mês
                <br>Possibilidade de gerenciar mais de 500 fúncionarios
                <br>Retorno de pacote de 1 hora.</p>
        </div>
        <div class="pcs"><a href='@Url.Action("Index", "Cadastro")#'><img src="img/computadores-4.jpg" alt=""></a></div>
        <br>
        <br>
        <br><p>.</p>
    </section>
<!-- footer -->
<footer class="footer">
    <div class="logos">
        <img src="img/logo-1.jpg" class="logo_footer">
        <h4>Ponto<br>
            Digital</h4>
    </div>
    <div>
        <div class="contatos">
            <h3>Contatos</h3>
        </div>
        <div class="email">
            <p>Empresa <br>
                Agoravai.01@hotmail.com <br>
                Agoravai.02@hotmail.com</p>
        </div>
    </div>
    <div class="telefones">
        <p>Telefones <br>
            (11) 4789-0938 <br>
            (11) 2894-8632</p>
    </div>
    <div class="judicial">
        <p>Judicial <br>
            <li><a href="#">Termos</a></li>
            <li><a href="#">Privacidade</a></li>
        </p>
    </div>

</footer>
<section>
    <div class="mapa">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14631.38951652919!2d-46.646406901276464!3d-23.537991115499356!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce582da261e6b1%3A0x5ceb2e6bcbc1483b!2sPaulista!5e0!3m2!1spt-BR!2sbr!4v1552677502951"
            width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</section>

Views/Login/Index.cshtml
@{
    Layout = "_Layout";
}
    <link rel="stylesheet" href="css/login.css">

    <section id="cadastro">
       
            <div id="area">
                    <form action='@Url.Action("Logar", "Login")' method="POST" id="formulario" autocomplete="off">
                      <fieldset>
                        <legend>Login</legend>
                        <div><label class="email">Email:</label><input class="campo_email" type="text" name="email" required><br></div>
                         <div><label class="senha">Senha:</label><input class="campo_senha" type="text" name="senha" required><br></div>
                        <input type="submit" value="Enviar" class="enviar">
                      </fieldset>
                    </form>
                </div>
            </section>
            <section>

                <p>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                </p>.
                
            </section>


</html>

Views/QuemSomos/Index.cshtml
@{
    Layout = "_Layout";
}
    <link rel="stylesheet" href="css/quemsomos.css">
    <header class="header">


            <section id="historia">
                <div class="hist">
                    <h3 class="h33">História</h3>
                    <p class="p_hist"> A empresa Agora Vai é um empresa especializada em <br>
                        desenvolvimento de softwares, fundada em 2012 por Carlos <br>
                        Tsukamoto e Cesar Sportore, acaba de desenvolver a última <br>
                        inovação do mercado computacional, o sistema operacional <br>
                        Ponto Digital</p>
                </div>
                <img class="imgbla" src="img/IMG-20190312-WA0010.jpg" alt="professores">
            </section>

            <section id="funcionarios">
                <img class="imgbla" src="img/IMG-20190317-WA0025.jpg" alt="funcionarios">
                <div class="func">
                    <h3 class="h24">Funcionários</h3>
                    <p class="p_func"> Watson: Especializado em Tipografia
                        <br>
                        Bruna: Especializada em Teoria das cores
                        <br>
                        Joyce: Especializada em Gestalt
                        <br>
                        Jhuan: Especializado em UX
                    </p>
                </div>
            </section>

            <section id="empresa">
                <img src="img/empresa_1.jpg" alt="" class="img_empresa1">
                <img src="img/empresa_2.jpg" alt="" class="img_empresa2">
                <img src="img/empresa_3.jpg" alt="" class="img_empresa3">
                <div class="empre">
                    <h3 class="h35">Empresa</h3>
                    <p class="p_empresa"> Localizada na Paulista e pensada para ser a melhor e mais produtiva <br>
                        do mercado nacional, desenvolvida pensando em melhorar o funcionamento <br>
                        das outras empresas, desenvolver softwares inovadores e alavancar o <br>
                        capital entre instituições pequenas e grandes com resultado de melhorar <br>
                        a economia brasileira.
                    </p>
                </div>
                <br>
                <br>
                <br>
                <br> <p>.</p>
            </section>

</html>

Views/Sac/Index.cshtml
@{
    Html.RenderPartial("_HeaderNavBar");
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/sac.css">
    <link href="https://fonts.googleapis.com/css?family=Barlow" rel="stylesheet">
    <title>Ponto digital</title>
</head>
  
    <header class="header">
       
    </header>
    <section>
        <div>
            <h3 class="duv">Dúvidas frenquentes</h3>
            <h4 class="h4">1. Nunca utilizei um software de gestão, quais são os desafios que posso enfrentar?</h4>
            <p class="pergunta">Provavelmente você e sua equipe encaram a divisão de tarefas através de fichas, post-its, quadro exposto
                na parede ou algo do tipo. Ou, talvez, vocês tentam se gerenciar de uma forma mais orgânica, sem
                documentar ou pautar física ou virtualmente as diversas tarefas da empresa. Neste caso, as maiores
                dificuldades serão em relação a resistir os antigos hábitos. Pois a partir do uso do sistema tudo
                mudará.
                Vocês precisarão alimentar o sistema com os dados dos jobs e das tarefas. Embora tudo seja muito rápido
                e prático, toda a equipe pode sentir um desconforto nos primeiros dias por estar passando por uma
                mudança. Contudo, garantimos que o esforço para mudar o comportamento de gestão é extremamente válido.
                A partir dos dados coletados dos jobs cadastrados e da organização que o sistema proporciona, sua
                empresa poderá mensurar e aumentar significativamente a produtividade, evitar erros de comunicação e
                inclusive melhorar a relação com os clientes por possuir informações concretas sobre seu fluxo de
                trabalho e prazos (inclusive podendo precificar mais precisamente seus trabalhos, garantindo a
                lucratividade dos contratos).</p>


            <h4 class="h4"> 2. Já utilizei vários softwares, mas nenhum funcionou 100%. O que devo fazer para não errar novamente?</h4>
            <p class="pergunta">Se você já utilizou outros sistemas e está chegando no Operand agora, saiba que nosso primeiro passo para
                atendê-lo é identificar suas características e os motivos pelos quais os outros sistemas não deram certo.
                Muitos de nossos clientes encontraram funcionalidades e uma organização de dados diferenciada em nosso
                sistema, por isso optaram pelo Operand. Porém, outros se queixam por não terem conseguido implantar o uso do
                outro sistema que tentaram. E é aqui que o Operand se destaca. Possuímos uma equipe dedicada a ajudá-lo com
                a implantação e uso do sistema, o departamento de Relacionamento.
                
                Nossa equipe quer ajudá-lo a usar o sistema da forma mais plena o possível. Por isso promovemos conversas
                sobre as dificuldades com as funcionalidades ou com o engajamento da equipe para utilizar os recursos
                disponíveis na ferramenta. E dos possíveis problemas, a equipe pode ser a barreira mais difícil de
                ultrapassar. Pois o sistema depende de cada um para ser alimentado e usado plenamente.
                
                Por isso, faça o máximo para engajar a equipe. Promova momentos de conversa e discussão sobre o sistema e
                seja um promotor do uso do sistema. Lembre a todos que utilizar a ferramenta trará muitos benefícios
                futuros, bastam um pouco de persistência e paciência.
            </p> 


            <h4 class="h4"> 3. Todos da minha equipe precisam ter acesso ao sistema?</h4>
            <p class="pergunta"> Isso varia muito de plataforma para plataforma. No Operand, indicamos que toda a equipe tenha acesso ao
            sistema, pois assim há uma maior participação dentro do próprio sistema. O que acaba acelerando processos e
            garantindo mais visão sobre produtividade, tarefas a fazer e mais informações relevantes para seu processo.

            Além disso, o Operand possui diversos módulos, possibilitando que todas as áreas interajam e executem suas
            tarefas de forma prática. Com todos dentro do sistema, a comunicação fica mais eficiente. As pautas serão
            divididas entre os usuários e o trabalho de cada um estará à vista – ajudando na mensuração de resultados.
            </p>
        </div>
    </section>

    <section>
        <h3 class="h36">Avaliações</h3>
        <img class="ugly" src="img/Funny-Twitter.png" alt="">
        <img class="sex" src="img/tweet.jpg" alt="">
    </section>

Views/Shared/_HeaderNavBar.cshtml
@{
    var user = (string) ViewData["User"];
    var adm = (string) ViewData["Adm"];
}

    @if ()
    {
        
    }

<nav class="menu">
            <!-- <a class="toggle-nav" href="#">&#9776;</a> -->
            <ul class="active">
                
                <li><a href='@Url.Action("Index", "Home")#Home'>Ponto Digital</a></li>   
                
                <li><img src="img/logo..jpg" class="logo"></li>

                <li>
                    <form class="search-form">
                        <input type="text" class="pesquisa">
                        <button class="search">Pesquisar</button>
                    </form>
                </li>
            </ul>
            <ul class="atalhos">
                <li>
                    <h2 class="slogan">Sua Empresa Em Seus Olhos</h2>
                </li>
                <li><a href='@Url.Action("Index", "QuemSomos")#QuemSomos'>Quem Somos</a></li>
                <li><a href='@Url.Action("Index", "Sac")#Sac'>Sac</a></li>
                <li><a href='@Url.Action("Index", "Cadastro")#Cadastro'>Cadastro</a></li>
               @if(string.IsNullOrEmpty(user))
               {
                    <li><a href='@Url.Action("Index","Login")'>Login</a></li>
               }else
               {
                    <li><a href='@Url.Action("Logout","Login")'>Logout</a></li>
               }
            </ul>
        </nav>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @if( (string) ViewData["TituloPag"] == "Comentarios"){
    <link rel="stylesheet" href="~/css/comentario.css">
        
}
    <title> @ViewData["TituloPag"] - Agora vai</title>
</head>
<body>
    
</body>
</html>
 <header class="header">
      
@{
    Html.RenderPartial("_HeaderNavBar");

}
             
           
<body class="flex-container">
    
    @RenderBody()
  

</body>
</html>
</html>